"""
Monolithic LPR MobileViT utilities: all submodules merged into one file.
Generated by assistant to flatten the project structure.
Original sources: src/lpr_mobilevit/*.py
"""
import os, re, math, random, csv
from dataclasses import dataclass
from typing import List, Tuple, Dict, Any, Optional
import numpy as np
import yaml
import cv2
import torch
import torch.nn as nn
import torch.nn.functional as F

# ---------------------- merged modules below ----------------------

# ===== File: utils.py =====
import os, random
import numpy as np
import yaml
import torch

def set_seed(seed: int = 42, deterministic: bool = False):
    random.seed(seed)
    np.random.seed(seed)
    torch.manual_seed(seed)
    torch.cuda.manual_seed_all(seed)
    if deterministic:
        torch.backends.cudnn.deterministic = True
        torch.backends.cudnn.benchmark = False
    else:
        torch.backends.cudnn.benchmark = True

def load_yaml(path: str) -> dict:
    with open(path, "r") as f:
        return yaml.safe_load(f)

# ===== File: charsets.py =====
import re, yaml, os
from dataclasses import dataclass
from typing import List, Optional, Tuple

# in src/lpr_mobilevit/charsets.py (add if missing)
NAMED_CHARSETS = {
    "digits": "0123456789",
    "letters": "ABCDEFGHIJKLMNOPQRSTUVWXYZ",
    "letters_no_ioq": "ABCDEFGHJKLMNPRSTUVWXYZ",
    # add any other names you referenced in YAML
}

@dataclass
class FormatConfig:
    pattern: str
    charsets: List[str]
    separators: List[str]
    @property
    def positions(self) -> int:
        # number of L/# tokens
        return sum(ch in ("L","#") for ch in self.pattern)

@dataclass
class Template:
    id: str
    pattern: str
    charsets: List[str]
    @property
    def positions(self) -> int:
        return sum(ch in ("L","#") for ch in self.pattern)

@dataclass
class MultiFormatConfig:
    separators: List[str]
    templates: List[Template]

# ----------------------------- loading -----------------------------

def load_yaml(path: str) -> dict:
    with open(path, "r", encoding="utf-8") as f:
        return yaml.safe_load(f)

def resolve_config_inheritance(path: str) -> dict:
    cfg = load_yaml(path)
    if "inherits" in cfg:
        base_path = os.path.join(os.path.dirname(path), cfg["inherits"])
        base = load_yaml(base_path)
        merged = dict(base)
        for k, v in cfg.items():
            if k == "inherits":
                continue
            merged[k] = v
        return merged
    return cfg

def load_format_config(path: str) -> FormatConfig:
    cfg = resolve_config_inheritance(path)
    fmt = cfg["format"]  # single-template files ONLY
    seps = cfg.get("separators", ["-","•","·"," "])
    return FormatConfig(pattern=fmt["pattern"], charsets=fmt["charsets"], separators=seps)

def load_multi_format_config(path: str) -> MultiFormatConfig:
    cfg = resolve_config_inheritance(path)
    seps = cfg.get("separators", ["-","•","·"," "])
    tpls = [Template(id=t["id"], pattern=t["pattern"], charsets=t["charsets"])
            for t in cfg["templates"]]
    return MultiFormatConfig(separators=seps, templates=tpls)

# ----------------------------- helpers -----------------------------

def strip_separators(s: str, separators: List[str]) -> str:
    out = s
    for sp in separators:
        out = out.replace(sp, "")
    return out

def pattern_to_regex(pattern: str, separators: List[str]) -> re.Pattern:
    # L -> [A-Z], # -> [0-9]; other chars are literals; allow optional separators in labels
    regex = []
    for ch in pattern:
        if ch == "L":
            regex.append("([A-Z])")
        elif ch == "#":
            regex.append("([0-9])")
        else:
            # literal separator
            regex.append(re.escape(ch))
    full = "^" + "".join(regex) + "$"
    return re.compile(full)

def encode_label_single(label: str, fmt: FormatConfig, uppercase: bool=True) -> List[int]:
    s = label.upper() if uppercase else label
    # remove separators to align with charsets positions
    s_compact = strip_separators(s, fmt.separators)
    if len(s_compact) != fmt.positions:
        raise ValueError(f"Label length {len(s_compact)} != positions {fmt.positions} for pattern {fmt.pattern}")
    indices = []
    pi = 0
    for token in fmt.pattern:
        if token in ("L","#"):
            ch = s_compact[pi]
            try:
                idx = fmt.charsets[pi].index(ch)
            except ValueError:
                raise ValueError(f"Character '{ch}' not in charset for position {pi}")
            indices.append(idx)
            pi += 1
    return indices

def try_match_template(label: str, mt: MultiFormatConfig) -> Optional[int]:
    s = label.upper()
    for i,t in enumerate(mt.templates):
        rx = pattern_to_regex(t.pattern, mt.separators)
        if rx.match(s):
            return i
    return None

def encode_label_multi(label: str, mt: MultiFormatConfig, template_idx: Optional[int], uppercase: bool=True) -> Tuple[int, List[int]]:
    s = label.upper() if uppercase else label
    if template_idx is None:
        template_idx = try_match_template(s, mt)
        if template_idx is None:
            raise ValueError(f"Could not match label '{label}' to any template")
    t = mt.templates[template_idx]
    # compact version
    compact = strip_separators(s, mt.separators)
    if len(compact) != t.positions:
        raise ValueError(f"Label '{label}' does not have expected number of tokens for template {t.id}")
    idxs = []
    for pos in range(t.positions):
        ch = compact[pos]
        charset = t.charsets[pos]
        ix = charset.find(ch)
        if ix < 0:
            raise ValueError(f"Character '{ch}' not allowed at position {pos} for template {t.id}")
        idxs.append(ix)
    return template_idx, idxs

# ===== File: augment.py =====
# Minimal, dependency-free augmentation/letterbox pipeline
# Exposes a callable with Albumentations-like API: tfms(image=img) -> {"image": torch.Tensor}
import math, random
from typing import Dict, Optional
import numpy as np
import cv2
import torch

IMAGENET_MEAN = np.array([0.485, 0.456, 0.406], dtype=np.float32)
IMAGENET_STD  = np.array([0.229, 0.224, 0.225], dtype=np.float32)

def letterbox(img, new_shape=(128, 256), color=(114,114,114)):
    h, w = img.shape[:2]
    new_h, new_w = new_shape
    r = min(new_w / w, new_h / h)
    resized = cv2.resize(img, (int(w * r), int(h * r)), interpolation=cv2.INTER_LINEAR)
    pad_w, pad_h = new_w - resized.shape[1], new_h - resized.shape[0]
    top = pad_h // 2
    bottom = pad_h - top
    left = pad_w // 2
    right = pad_w - left
    out = cv2.copyMakeBorder(resized, top, bottom, left, right, cv2.BORDER_CONSTANT, value=color)
    return out

def _random_brightness_contrast(img, b=0.15, c=0.15):
    """
    Supports two APIs:

    1) Legacy scalar magnitudes (additive brightness, multiplicative contrast around 1):
         - b: float in [0, ..] → brightness shift magnitude as a fraction of 255
         - c: float in [0, ..] → contrast jitter magnitude (alpha = 1 ± c)

    2) YAML-style ranges (multiplicative factors):
         - b: (bmin, bmax) brightness multiplier range, e.g. (0.75, 1.25)
         - c: (cmin, cmax) contrast multiplier range around image mean, e.g. (0.75, 1.25)
    """

    # If ranges (tuple/list) are provided → multiplicative semantics
    if isinstance(b, (tuple, list)) or isinstance(c, (tuple, list)):
        img = img.astype(np.float32)

        # Brightness multiplier (simple gain)
        if isinstance(b, (tuple, list)) and len(b) == 2:
            bf = random.uniform(float(b[0]), float(b[1]))
            img = img * bf
        elif isinstance(b, (int, float)) and b > 0:
            # legacy additive brightness shift
            beta = 255.0 * random.uniform(-float(b), float(b))
            img = img + beta

        # Contrast multiplier around the mean
        if isinstance(c, (tuple, list)) and len(c) == 2:
            cf = random.uniform(float(c[0]), float(c[1]))
            m = img.mean(axis=(0, 1), keepdims=True)
            img = (img - m) * cf + m
        elif isinstance(c, (int, float)) and c > 0:
            # legacy multiplicative contrast jitter
            alpha = 1.0 + random.uniform(-float(c), float(c))
            img = img * alpha

        img = np.clip(img, 0, 255).astype(np.uint8)
        return img

    # Legacy scalar path (both b and c are floats)
    if (isinstance(b, (int, float)) and b > 0) or (isinstance(c, (int, float)) and c > 0):
        alpha = 1.0 + random.uniform(-float(c), float(c)) if c > 0 else 1.0
        beta  = 255.0 * random.uniform(-float(b), float(b)) if b > 0 else 0.0
        img = np.clip(alpha * img + beta, 0, 255).astype(np.uint8)
    return img

def _random_motion_blur(img, p=0.15, k=(3,5)):
    if random.random() > p:
        return img
    ksize = random.choice(list(range(k[0], k[1]+1, 2)))
    kernel = np.zeros((ksize, ksize), dtype=np.float32)
    xs = random.choice([0,1])
    if xs == 0:
        kernel[ksize//2, :] = 1.0 / ksize
    else:
        kernel[:, ksize//2] = 1.0 / ksize
    return cv2.filter2D(img, -1, kernel)

def _random_perspective(img, p=0.2, max_warp=0.03):
    if random.random() > p:
        return img
    h, w = img.shape[:2]
    dx = max(1, int(max_warp * w))
    dy = max(1, int(max_warp * h))
    src = np.float32([[0,0],[w-1,0],[w-1,h-1],[0,h-1]])
    dst = np.float32([
        [random.randint(0,dx), random.randint(0,dy)],
        [w-1-random.randint(0,dx), random.randint(0,dy)],
        [w-1-random.randint(0,dx), h-1-random.randint(0,dy)],
        [random.randint(0,dx), h-1-random.randint(0,dy)]
    ])
    M = cv2.getPerspectiveTransform(src, dst)
    return cv2.warpPerspective(img, M, (w, h), flags=cv2.INTER_LINEAR, borderMode=cv2.BORDER_CONSTANT, borderValue=(114,114,114))

def _extract_mean_std(cfg: dict | None):
    mean, std = IMAGENET_MEAN, IMAGENET_STD
    if isinstance(cfg, dict):
        # Preferred location
        if isinstance(cfg.get("input"), dict):
            if isinstance(cfg["input"].get("mean"), (list,tuple)):
                mean = np.array(cfg["input"]["mean"], dtype=np.float32)
            if isinstance(cfg["input"].get("std"), (list,tuple)):
                std  = np.array(cfg["input"]["std"],  dtype=np.float32)
        # Fallback (top-level)
        if isinstance(cfg.get("input_mean"), (list,tuple)):
            mean = np.array(cfg["input_mean"], dtype=np.float32)
        if isinstance(cfg.get("input_std"), (list,tuple)):
            std  = np.array(cfg["input_std"], dtype=np.float32)
    return mean, std

class _Compose:
    def __init__(self, height: int, width: int, train: bool,
                 aug_cfg: Optional[dict] = None, mean=None, std=None):
        self.height = int(height)
        self.width  = int(width)
        self.train  = bool(train)
        self.aug    = aug_cfg or {}
        self.mean   = IMAGENET_MEAN if mean is None else np.array(mean, dtype=np.float32)
        self.std    = IMAGENET_STD  if std  is None else np.array(std, dtype=np.float32)

    def __call__(self, image) -> Dict[str, torch.Tensor]:
        img = image
        img = letterbox(img, (self.height, self.width))
        if self.train:
            p_persp = float(self.aug.get("perspective_prob", self.aug.get("persp_prob", 0.25)))
            max_warp = float(self.aug.get("max_warp", 0.04))
            p_mblur  = float(self.aug.get("motion_blur_prob", 0.20))
            b_rng    = tuple(self.aug.get("brightness", [0.88, 1.12]))
            c_rng    = tuple(self.aug.get("contrast",   [0.90, 1.10]))
            img = _random_perspective(img, p=p_persp, max_warp=max_warp)
            img = _random_motion_blur(img, p=p_mblur, k=(3,7))
            img = _random_brightness_contrast(img, b=b_rng, c=c_rng)

        img = img.astype(np.float32) / 255.0
        img = (img - self.mean) / self.std
        tensor = torch.from_numpy(img).permute(2,0,1).contiguous()
        return {"image": tensor}

def build_train_augs(height: int, width: int, cfg: dict | None = None):
    mean, std = _extract_mean_std(cfg)
    aug = cfg.get("augment", {}) if isinstance(cfg, dict) else None
    return _Compose(height, width, train=True, aug_cfg=aug, mean=mean, std=std)

def build_val_augs(height: int, width: int, cfg: dict | None = None):
    mean, std = _extract_mean_std(cfg)
    return _Compose(height, width, train=False, aug_cfg=None, mean=mean, std=std)

# ===== File: decoding_utils.py =====
# src/lpr_mobilevit/decoding_utils.py
# Utilities for robust decoding at inference time:
# - confidence gating
# - char-level Top-K re-scoring (beam search over low-gap slots)
# These helpers operate on gathered logits for a *single* chosen template.

from typing import List, Tuple, Dict, Any
import numpy as np
import torch
import math

def _softmax_np(x: np.ndarray, axis: int = -1) -> np.ndarray:
    x = x - np.max(x, axis=axis, keepdims=True)
    e = np.exp(x)
    return e / np.sum(e, axis=axis, keepdims=True)

def per_slot_topk(gathered_logits: torch.Tensor, slot_charsets: List[str], pos_mask: List[bool], k: int = 2):
    """
    gathered_logits: [Pmax, Cmax] (torch) for one sample
    slot_charsets:   list[str]  characters allowed for each valid slot (length == num_valid_slots)
    pos_mask:        list[bool] length Pmax; True where a slot is valid, else padded
    Returns:
      topk_idx: List[np.ndarray]  (num_slots, k) indices in charset
      topk_prob: List[np.ndarray] (num_slots, k) softmax probs
    """
    assert gathered_logits.ndim == 2, "Expect [Pmax, Cmax]"
    g = gathered_logits.detach().cpu().numpy()
    topk_idx, topk_prob = [], []
    slot = 0
    for p, valid in enumerate(pos_mask):
        if not valid: 
            continue
        nC = len(slot_charsets[slot])
        v = g[p, :nC].astype(np.float32)
        prob = _softmax_np(v, axis=0)
        idx = np.argsort(-prob)[:k]
        topk_idx.append(idx)
        topk_prob.append(prob[idx])
        slot += 1
    return topk_idx, topk_prob

def stitch_from_indices(top_idx: List[int], slot_charsets: List[str], pattern: str) -> Tuple[str, str]:
    """
    Build (text, text_raw) given per-slot chosen indices and the template pattern.
    """
    chars = [slot_charsets[i][idx] for i, idx in enumerate(top_idx)]
    out, raw = [], []
    s = 0
    for ch in pattern:
        if ch in ('L', '#'):
            out.append(chars[s]); raw.append(chars[s]); s += 1
        else:
            out.append(ch)
    return ''.join(out), ''.join(raw)

def score_indices(sum_logits_np: List[np.ndarray], top_idx: List[int]) -> float:
    """
    Compute sum log prob given softmax probs lists per slot.
    """
    s = 0.0
    for i, idx in enumerate(top_idx):
        prob = float(sum_logits_np[i][idx])
        s += math.log(max(prob, 1e-9))
    return s

def charlevel_beam_rescore(gathered_logits_b: torch.Tensor,
                           slot_charsets: List[str],
                           pos_mask: List[bool],
                           pattern: str,
                           topk: int = 2,
                           max_flips: int = 2,
                           gap_delta: float = 0.20) -> Dict[str, Any]:
    """
    Return best candidate among:
     - top-1 string (baseline)
     - candidates formed by flipping up to `max_flips` slots to their 2nd-best option
       (only for slots where (p1 - p2) < gap_delta).
    Returns dict with keys: text, text_raw, avg_conf, used_beam(bool), flips(int)
    """
    # Top-k per slot
    tk_idx, tk_prob = per_slot_topk(gathered_logits_b, slot_charsets, pos_mask, k=topk)
    # baseline
    top1_idx = [int(idx[0]) for idx in tk_idx]
    base_text, base_raw = stitch_from_indices(top1_idx, slot_charsets, pattern)
    base_conf = float(np.mean([p[0] for p in tk_prob]))
    best = dict(text=base_text, text_raw=base_raw, avg_conf=base_conf, used_beam=False, flips=0, top_idx=top1_idx)

    # Identify ambiguous slots where gap < delta
    ambiguous = [i for i,(prob) in enumerate(tk_prob) if len(prob) >= 2 and (prob[0]-prob[1]) < gap_delta]
    ambiguous = ambiguous[:8]  # safety cap

    if not ambiguous or max_flips <= 0:
        return best

    # Precompute logprob arrays
    sum_logits_np = [p for p in tk_prob]

    # Try combinations of flipping up to max_flips slots
    from itertools import combinations
    def score_of(idx_list): return score_indices(sum_logits_np, idx_list)
    best_score = score_of(best['top_idx'])

    for r in range(1, min(max_flips, len(ambiguous)) + 1):
        for combo in combinations(ambiguous, r):
            cand = list(best['top_idx'])
            ok = True
            for i in combo:
                if len(tk_idx[i]) >= 2:
                    cand[i] = int(tk_idx[i][1])  # use 2nd best
                else:
                    ok = False; break
            if not ok: 
                continue
            s = score_of(cand)
            if s > best_score:
                text, raw = stitch_from_indices(cand, slot_charsets, pattern)
                conf = float(np.mean([sum_logits_np[i][cand[i]] for i in range(len(cand))]))
                best.update(text=text, text_raw=raw, avg_conf=conf, used_beam=True, flips=r, top_idx=cand)
                best_score = s

    return best

# ===== File: dataset.py =====
import os, csv
from typing import List, Tuple, Optional
import cv2
import torch
from torch.utils.data import Dataset
# [merged] removed relative import from .charsets

# --- add this helper ---
def _resolve_csv_path(csv_path: str, p: str) -> str:
    """
    Resolve a row's 'path' robustly:
      - absolute paths are returned as-is
      - otherwise try:
        (a) relative to CSV dir
        (b) relative to the *parent* of CSV dir  (handles rows like 'tiny_dataset/...' when
            the CSV lives in '.../tiny_dataset/')
        (c) as-is from current working dir (last resort)
    """
    p = p.strip()
    if os.path.isabs(p):
        return os.path.normpath(p)

    csv_dir = os.path.dirname(os.path.abspath(csv_path))
    # (a) CSV dir
    cand1 = os.path.normpath(os.path.join(csv_dir, p))
    if os.path.exists(cand1):
        return cand1

    # (b) Parent of CSV dir — fixes the 'tiny_dataset/tiny_dataset' duplication case
    parent = os.path.dirname(csv_dir)
    cand2 = os.path.normpath(os.path.join(parent, p))
    if os.path.exists(cand2):
        return cand2

    # (c) Fallback: treat p relative to CWD
    return os.path.normpath(os.path.abspath(p))

class LPDataset(Dataset):
    """
    CSV columns: path,label
    """
    def __init__(self, csv_path: str, fmt: FormatConfig, transform=None, drop_invalid=True, uppercase=True):
        self.fmt = fmt
        self.transform = transform
        self.uppercase = uppercase
        self.samples = []
        with open(csv_path, "r") as f:
            reader = csv.DictReader(f)
            for row in reader:
                p = _resolve_csv_path(csv_path, row["path"])   # <-- use helper
                y = row["label"]
                try:
                    idxs = encode_label_single(y, fmt, uppercase=uppercase)
                    self.samples.append((p, idxs))
                except Exception as e:
                    if not drop_invalid:
                        raise
        if len(self.samples) == 0:
            raise RuntimeError("No valid samples found in CSV.")

    def __len__(self): return len(self.samples)

    def __getitem__(self, i):
        p, idxs = self.samples[i]
        img = cv2.imread(p, cv2.IMREAD_COLOR)
        if img is None:
            raise FileNotFoundError(p)
        img = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)
        if self.transform is not None:
            img = self.transform(image=img)["image"]
        else:
            import numpy as np
            img = torch.from_numpy(img.transpose(2,0,1)).float()/255.0
        y = torch.tensor(idxs, dtype=torch.long)
        return img, y, p

class LPDatasetMT(Dataset):
    """
    CSV columns: path,label[,template_id]
    If template_id is absent, we auto-match via regex from YAML.
    """
    def __init__(self, csv_path: str, mt_cfg: MultiFormatConfig, transform=None,
                 template_col: Optional[str]="template_id", drop_unmatched=True,
                 uppercase=True, ignore_index: int=-100):
        self.mt = mt_cfg
        self.transform = transform
        self.uppercase = uppercase
        self.ignore_index = ignore_index
        self.samples = []  # (path, idxs, t_idx)
        with open(csv_path, "r") as f:
            reader = csv.DictReader(f)
            for row in reader:
                p = _resolve_csv_path(csv_path, row["path"])   # <-- use helper
                y = row["label"]
                t_idx = None
                if template_col and (template_col in row) and row[template_col] not in (None,""):
                    # find by id
                    ids = [t.id for t in self.mt.templates]
                    try:
                        t_idx = ids.index(row[template_col])
                    except ValueError:
                        # allow integer index
                        try:
                            t_idx = int(row[template_col])
                        except:
                            t_idx = None
                try:
                    t_idx, idxs = encode_label_multi(y, self.mt, t_idx, uppercase=uppercase)
                    self.samples.append((p, idxs, t_idx))
                except Exception as e:
                    if not drop_unmatched:
                        raise
        if len(self.samples) == 0:
            raise RuntimeError("No valid samples found in CSV.")

    def __len__(self): return len(self.samples)

    def __getitem__(self, i):
        p, idxs, t_idx = self.samples[i]
        img = cv2.imread(p, cv2.IMREAD_COLOR)
        if img is None:
            raise FileNotFoundError(p)
        img = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)
        if self.transform is not None:
            img = self.transform(image=img)["image"]
        y = torch.tensor(idxs, dtype=torch.long)
        t = torch.tensor(t_idx, dtype=torch.long)
        # mask will be built in collate
        return img, y, t, p

def collate_mt(batch, ignore_index: int=-100, Pmax: Optional[int]=None):
    """
    Batch of (img, y, t, path) with variable length y.
    Returns: images[B,3,H,W], y_pad[B,Pmax], t_idx[B], mask[B,Pmax], paths[list]
    """
    imgs, ys, tids, paths = [], [], [], []
    for (im, y, t, p) in batch:
        imgs.append(im); ys.append(y); tids.append(t); paths.append(p)
    imgs = torch.stack(imgs, dim=0)
    tids = torch.stack(tids, dim=0)
    if Pmax is None:
        Pmax = max([len(y) for y in ys])
    y_pad = torch.full((len(batch), Pmax), fill_value=ignore_index, dtype=torch.long)
    mask = torch.zeros((len(batch), Pmax), dtype=torch.bool)
    for i,y in enumerate(ys):
        L = len(y)
        y_pad[i, :L] = y
        mask[i, :L] = True
    return imgs, y_pad, tids, mask, paths

# ===== File: metrics.py =====
import torch
from typing import List, Tuple

def accuracy_metrics(logits: List[torch.Tensor], targets: torch.Tensor) -> Tuple[float,float]:
    """
    For single-template evaluation.
    logits: list of [B, Ci]; targets: [B, N]
    """
    with torch.no_grad():
        preds = [l.argmax(dim=1) for l in logits]   # list of [B]
        preds = torch.stack(preds, dim=1)           # [B,N]
        correct = (preds == targets)
        char_acc = correct.float().mean().item()
        plate_acc = correct.all(dim=1).float().mean().item()
        return char_acc, plate_acc

# ===== File: multipath_head.py =====
import torch
import torch.nn as nn
from typing import List, Dict, Optional, Tuple

# ------------------------------ Single-template heads ------------------------------

class MultiPathHead(nn.Module):
    def __init__(self, in_dim: int, num_classes: List[int], hidden: int = 512, dropout: float = 0.1):
        super().__init__()
        self.N = len(num_classes)
        self.heads = nn.ModuleList([
            nn.Sequential(
                nn.Linear(in_dim, hidden),
                nn.GELU(),
                nn.Dropout(dropout),
                nn.Linear(hidden, C),
            )
            for C in num_classes
        ])

    def forward(self, g: torch.Tensor) -> List[torch.Tensor]:
        return [h(g) for h in self.heads]

class MultiPathOCR(nn.Module):
    def __init__(self, backbone: nn.Module, num_classes: List[int], hidden: int = 512, dropout: float = 0.1):
        super().__init__()
        self.backbone = backbone
        self.head = MultiPathHead(backbone.out_channels, num_classes, hidden=hidden, dropout=dropout)

    def forward(self, x) -> List[torch.Tensor]:
        g = self.backbone(x)
        logits = self.head(g)
        return logits

# ------------------------------ Multi-template router ------------------------------

class _FormatClassifier(nn.Module):
    def __init__(self, in_dim: int, n_templates: int, hidden: int = 256, dropout: float = 0.1):
        super().__init__()
        self.net = nn.Sequential(
            nn.Linear(in_dim, hidden),
            nn.GELU(),
            nn.Dropout(dropout),
            nn.Linear(hidden, n_templates),
        )
    def forward(self, g: torch.Tensor) -> torch.Tensor:
        return self.net(g)

class _TemplateHeads(nn.Module):
    def __init__(self, in_dim: int, num_classes: List[int], hidden: int = 512, dropout: float = 0.1):
        super().__init__()
        self.paths = nn.ModuleList([
            nn.Sequential(
                nn.Linear(in_dim, hidden),
                nn.GELU(),
                nn.Dropout(dropout),
                nn.Linear(hidden, C),
            ) for C in num_classes
        ])
        self.positions = len(num_classes)
    def forward(self, g: torch.Tensor) -> List[torch.Tensor]:
        return [p(g) for p in self.paths]

class MultiTemplateOCR(nn.Module):
    def __init__(self, backbone: nn.Module, num_classes_per_template: List[List[int]],
                 fmt_hidden: int = 256, head_hidden: int = 512, head_dropout: float = 0.1):
        super().__init__()
        self.backbone = backbone
        self.T = len(num_classes_per_template)
        self.heads = nn.ModuleList([
            _TemplateHeads(backbone.out_channels, ncs, hidden=head_hidden, dropout=head_dropout)
            for ncs in num_classes_per_template
        ])
        self.positions_per_template = [len(ncs) for ncs in num_classes_per_template]
        self.Pmax = max(self.positions_per_template)
        self.format = _FormatClassifier(backbone.out_channels, self.T, hidden=fmt_hidden, dropout=head_dropout)

    def forward(self, x):
        g = self.backbone(x)
        fmt_logits = self.format(g)
        tpl_logits = [head(g) for head in self.heads]
        return fmt_logits, tpl_logits

    def loss_multi(self, outputs, targets_pad, template_idx, mask, lambda_fmt=0.2, ignore_index=-100, class_weights=None):
        fmt_logits, tpl_logits = outputs
        loss = nn.CrossEntropyLoss()(fmt_logits, template_idx) * float(lambda_fmt)
        for t, head_logits in enumerate(tpl_logits):
            sel = (template_idx == t)
            if not torch.any(sel):
                continue
            Nt = len(head_logits)
            for pos in range(Nt):
                logit = head_logits[pos][sel]
                y = targets_pad[sel, pos]
                if class_weights is not None and class_weights[t][pos] is not None:
                    ce = nn.CrossEntropyLoss(weight=class_weights[t][pos].to(logit.device), ignore_index=ignore_index)
                else:
                    ce = nn.CrossEntropyLoss(ignore_index=ignore_index)
                loss = loss + ce(logit, y)
        return loss

    @torch.no_grad()
    def decode(self, outputs, charsets_per_template, topk_templates: int=1):
        fmt_logits, tpl_logits = outputs
        fmt_prob = fmt_logits.softmax(dim=1)
        fmt_conf, tids = fmt_prob.max(dim=1)
        B = fmt_logits.size(0)
        texts, confs, tids_out = [], [], []
        for i in range(B):
            t = int(tids[i].item())
            tids_out.append(t)
            positions = len(tpl_logits[t])
            s = []; csum = 0.0
            for pos in range(positions):
                p = tpl_logits[t][pos][i].softmax(dim=0)
                conf, idx = p.max(dim=0)
                s.append(charsets_per_template[t][pos][int(idx.item())])
                csum += float(conf.item())
            texts.append(''.join(s))
            confs.append((csum / max(1,positions)) * float(fmt_conf[i].item()))
        return texts, confs, tids_out

# ===== File: model_mobilevit.py =====
import torch
import torch.nn as nn
import torch.nn.functional as F

# ---- basic conv ----
class ConvBNAct(nn.Module):
    def __init__(self, in_ch, out_ch, k=3, s=1, p=None):
        super().__init__()
        if p is None: p = k//2
        self.conv = nn.Conv2d(in_ch, out_ch, k, s, p, bias=False)
        self.bn = nn.BatchNorm2d(out_ch)
        self.act = nn.SiLU(inplace=True)
    def forward(self, x):
        return self.act(self.bn(self.conv(x)))

# ---- MBConv (MobileNetV2 style inverted residual) ----
class MBConv(nn.Module):
    def __init__(self, in_ch, out_ch, s=1, expand=4):
        super().__init__()
        mid = in_ch * expand
        self.use_res = (s == 1 and in_ch == out_ch)
        self.block = nn.Sequential(
            # 1x1 expand
            nn.Conv2d(in_ch, mid, 1, 1, 0, bias=False),
            nn.BatchNorm2d(mid),
            nn.SiLU(inplace=True),
            # 3x3 depthwise
            nn.Conv2d(mid, mid, 3, s, 1, groups=mid, bias=False),
            nn.BatchNorm2d(mid),
            nn.SiLU(inplace=True),
            # 1x1 project
            nn.Conv2d(mid, out_ch, 1, 1, 0, bias=False),
            nn.BatchNorm2d(out_ch),
        )
    def forward(self, x):
        out = self.block(x)
        if self.use_res:
            out = out + x
        return out

# ---- Transformer layer (norm-first encoder) ----
def _make_transformer(d_model: int, nhead: int = 4, dim_feedforward: int = None, dropout: float = 0.0):
    if dim_feedforward is None:
        dim_feedforward = d_model * 2  # MobileViT uses 2d instead of 4d
    layer = nn.TransformerEncoderLayer(d_model=d_model, nhead=nhead, dim_feedforward=dim_feedforward,
                                       dropout=dropout, activation='gelu', batch_first=True, norm_first=True)
    return nn.TransformerEncoder(layer, num_layers=1)

class MobileViTBlock(nn.Module):
    def __init__(self, c_in: int, d_model: int, L: int = 2, patch: int = 2):
        super().__init__()
        self.patch = patch
        self.local = nn.Sequential(
            ConvBNAct(c_in, c_in, k=3, s=1),
            nn.Conv2d(c_in, d_model, 1, 1, 0, bias=False),
            nn.BatchNorm2d(d_model),
            nn.SiLU(inplace=True)
        )
        self.transformers = nn.ModuleList([_make_transformer(d_model) for _ in range(L)])
        self.proj = nn.Conv2d(d_model, c_in, 1, 1, 0, bias=False)
        self.fuse = ConvBNAct(c_in*2, c_in, k=3, s=1)

    def forward(self, x):
        B, C, H, W = x.shape
        p = self.patch
        assert (H % p == 0) and (W % p == 0), f"H and W must be multiples of patch={p}. Got {H}x{W}"

        y_local = self.local(x)                     # [B, d, H, W]
        d = y_local.shape[1]

        # Unfold into patches of size p x p with stride p
        unfold = F.unfold(y_local, kernel_size=p, stride=p)    # [B, d*p*p, N]
        N = unfold.shape[-1]
        # Reshape to [B*p*p, N, d]
        y = unfold.transpose(1,2).contiguous().view(B, N, d*p*p)
        # But we want P sequences (p*p), each with [B, N, d]
        y = unfold.view(B, d, p*p, N).permute(0,2,3,1).contiguous()  # [B, P, N, d]
        y = y.view(B*p*p, N, d)

        # Apply L transformer layers
        for enc in self.transformers:
            y = enc(y)  # [B*P, N, d]

        # Fold back
        y = y.view(B, p*p, N, d).permute(0,3,1,2).contiguous()  # [B, d, P, N]
        y = y.view(B, d*p*p, N)
        y = F.fold(y, output_size=(H, W), kernel_size=p, stride=p)   # [B, d, H, W]

        y = self.proj(y)                             # [B, C, H, W]
        out = self.fuse(torch.cat([x, y], dim=1))    # [B, C, H, W]
        return out

class MobileViTBackbone(nn.Module):
    """
    Returns global pooled feature vector g: [B, C_out]
    """
    def __init__(self, in_ch=3, channels=(64,80,96), dims=(96,120,144), depths=(2,4,3), patch=2, expand=4):
        super().__init__()
        c1, c2, c3 = channels
        d1, d2, d3 = dims
        L1, L2, L3 = depths
        self.patch = patch

        self.stem = ConvBNAct(in_ch, 16, k=3, s=2)
        self.mv2_1 = MBConv(16, 16, s=1, expand=expand)
        self.mv2_2 = MBConv(16, 24, s=2, expand=expand)  # 1/4
        self.mv2_3 = MBConv(24, c1, s=1, expand=expand)
        self.mvit_1 = MobileViTBlock(c_in=c1, d_model=d1, L=L1, patch=patch)

        self.mv2_4 = MBConv(c1, c2, s=2, expand=expand)  # 1/8
        self.mvit_2 = MobileViTBlock(c_in=c2, d_model=d2, L=L2, patch=patch)

        self.mv2_5 = MBConv(c2, c3, s=2, expand=expand)  # 1/16
        self.mvit_3 = MobileViTBlock(c_in=c3, d_model=d3, L=L3, patch=patch)

        self.out_channels = c3
        self.gap = nn.AdaptiveAvgPool2d((1,1))

    def forward(self, x):
        x = self.stem(x)
        x = self.mv2_1(x)
        x = self.mv2_2(x)
        x = self.mv2_3(x)
        x = self.mvit_1(x)
        x = self.mv2_4(x)
        x = self.mvit_2(x)
        x = self.mv2_5(x)
        x = self.mvit_3(x)
        g = self.gap(x).flatten(1)
        return g

